version: '1.0'
stages:
- checkout
- build
- push
steps:
  main_clone:
    title: Cloning main repository...
    type: git-clone
    stage: checkout
    repo: 'timlimhk/cf-example-build-and-push'
    revision: 'master'
    git: github-1
  build_my_app:
    title: Building Node.Js Docker Image
    type: build
    stage: build
    image_name: timlimhk/my-node-js-app
    working_directory: '.'
    tag: 'master'
    dockerfile: Dockerfile
  push_to_my_registry:
    stage: 'push'
    type: push
    title: Pushing to a registry
    candidate: ${{build_my_app}}
    tag: 'v1.0.0'
    registry: dk-repos
    image_name: timlimhk/my-node-js-app
